### ISSUE TITLE
constrain log length (otherwise elk dies)

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/enochecker3#15]
cc @ldruschk

**Comment by Sinitax** [comment]
@Trolldemorted to what length?

**Comment by Trolldemorted** [comment]
I think the (default) limit on indexable string fields enforced by ES is 32kb, but we could also check whether things have changed with the version upgrades, if 32k chars is not enough

**Comment by Sinitax** [comment]
Quick google search showed its stayed at around 32kb, actually 32766 (< 32768).
